### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by heeheehahanoodlesoop** [3kh0/3kh0.github.io#243] opened 2022-11-02 14:53 UTC
### Name

Ryan Nelson

### Review

Yaknow, I am extremely proud that this page is 1,000,000 times longer than my you-know-what. These games take so long to load though, but I'm fine with it since I can make some milk while I'm waiting. I get no girls though, so that's how desperate I am.

### Profile picture

![Myself](https://user-images.githubusercontent.com/115120915/199522500-4eba2ff1-c7b5-455f-adcc-01a67a01a2d1.png)

**Comment by 1mBounty** [comment] 2022-11-02 20:52
This is the same person as #175. Is that allowed @3kh0?

**Comment by 3kh0** [comment] 2022-11-02 21:00
Duplicate of #175

**Closed by 3kh0** 2022-11-02 21:00 UTC
Labels: 📄 Duplicate, ✏️ Review
