### ISSUE TITLE
[Bug] Eaglercraft buttons not lining up properly

### ISSUE THREAD

**Issue by Lando2202** [3kh0/3kh0.github.io#442] opened 2022-12-08 20:30 UTC
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [X] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

_https://3kh0.github.io/projects/minecraft-15/index.html_ whenever I want to create a world I have to move my cursor way above the button in order to be able to click it its the same for crafting and everything else

**Comment by 3kh0** [comment] 2022-12-09 03:00
@Lando2202 I am not able to partly able to reproduce this bug, can you check your extensions? Try disabling adblock or any other content blocker

**Comment by 3kh0** [comment] 2022-12-09 04:07
Duplicate of #441

**Closed by 3kh0** 2022-12-09 04:07 UTC
Labels: 🐜 Bug, 📄 Duplicate
