### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Shashplay** [3kh0/3kh0.github.io#420] opened 2022-12-05 16:39 UTC
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

When I enter it doesn't open and shows an
![Screenshot 2022-12-05 11 39 20 AM](https://user-images.githubusercontent.com/119881192/205692554-082e86e9-8dbf-4a5a-bae2-a58683e102ce.png)
 error

**Comment by 3kh0** [comment] 2022-12-05 22:25
Duplicate of #409

**Closed by 3kh0** 2022-12-05 22:25 UTC
Labels: 🐜 Bug, 📄 Duplicate
