### ISSUE TITLE
Add N Game

### ISSUE THREAD

**Issue by lukemattle** [3kh0/3kh0.github.io#600] opened 2023-01-07 11:55 UTC
### What is this request?

New game

### Please describe the new feature here

Add N Game (flash)
Gud game
https://kippykip.com/index.php?threads/n-flash-game-swfs.396/
(Use v2)

**Comment by B0UNTYINFINITY** [comment] 2023-01-18 20:13
Dupe of #429

**Closed** 2023-01-18 22:48 UTC
Labels: ✨ Enhancement
