### ISSUE TITLE
Load games from JSON file

### ISSUE THREAD

**Issue by Russell2259** [3kh0/3kh0.github.io#640] opened 2023-01-14 00:40 UTC
### What is this request?

New game

### Please describe the new feature here

Load the games from a singular JSON file.

html:
```html
<div id="search" class="flex-container">
<!--Games would generate here-->
</div>
```

javascript:
```javascript
fetch('./games.json')
  .then(res => res.json())
  .then(games => {
    games.forEach(game => {
      var gameEl = document.createElement('a');
      gameEl.classList = 'game-link container';
      gameEl.href = game.path
      gameEl.innerHTML = `<div class="game-tile"><img class="game-icon" src="${game.icon}" alt="icon" loading="lazy" /><h1 class="game-title">${game.title}</h1></div>`;
      document.querySelector('#search').appendChild(gameEl);
    });
  });
```
json:
```json
[
    {
        "path": "./projects/game",
        "name": "game name",
        "icon": "./projects/path to game icon"
    }
]
```

**Comment by mdoryammilwalrus** [comment] 2023-01-14 01:32
#335

**Comment by mdoryammilwalrus** [comment] 2023-01-14 01:33
#332

**Comment by 3kh0** [comment] 2023-01-14 13:13
Duplicate of #332

**Closed by 3kh0** 2023-01-14 13:13 UTC
Labels: 📄 Duplicate, ✨ Enhancement
