### ISSUE TITLE
[Bug] Eaglercraft 404 error (duplicate)

### ISSUE THREAD

**Issue by Yaran779** [3kh0/3kh0.github.io#410] opened 2022-12-03 20:33 UTC
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

There is a error code
This is the link to minecraft
https://3kh0.github.io/projects/minecraft/index.html
But i cant play because there is an error code for this.

**Comment by 3kh0** [comment] 2022-12-03 21:39
Use this link: https://3kh0.github.io/projects/minecraft-15/index.html

Let me know if it works!

**Comment by JEFFERYBAZOES** [comment] 2022-12-03 22:07
use this link its the new server https://3kh0.github.io/projects/minecraft-15/index.html

**Comment by Yaran779** [comment] 2022-12-03 22:43
> Use this link: https://3kh0.github.io/projects/minecraft-15/index.html
> 
> Let me know if it works!

Thank you. 
Or else i wouldve wasted alot of time

**Comment by 3kh0** [comment] 2022-12-03 23:47
Duplicate of #412

**Closed** 2022-12-03 23:48 UTC
Labels: 🐜 Bug, 📄 Duplicate
