### ISSUE TITLE
404 error on egealrcrft

### ISSUE THREAD

**Issue by Jman8977** [3kh0/3kh0.github.io#413] opened 2022-12-04 01:24 UTC
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

So this just happened right now but whenever I try to open eaglercraft it says 404 error, I've tried refreshing it and everything but it didn't work.  I don't know if this is happening to anyone else but plz help I really don't wanna lose my data!

![Screenshot 2022-12-03 5 23 12 PM](https://user-images.githubusercontent.com/119768265/205469508-fda05fdf-dd6d-441a-90d3-8540ba88d85a.png)

**Comment by 3kh0** [comment] 2022-12-04 01:43
Duplicate of #410, please refer to that issue

**Closed by 3kh0** 2022-12-04 01:43 UTC
Labels: 🐜 Bug, 📄 Duplicate

**Comment by JEFFERYBAZOES** [comment] 2022-12-04 02:10
this happened to me just click on this link for the new one https://3kh0.github.io/projects/minecraft-15/index.html

**Comment by 3kh0** [comment] 2022-12-04 03:02
open a new issue
