### ISSUE TITLE
Website blocked

### ISSUE THREAD

**Issue by pwksmsmsm** [3kh0/3kh0.github.io#147] opened 2022-03-17 17:28 UTC
roblox link wont work

**Comment by Pepperoni-png** [comment] 2022-03-17 17:30
This website doesn't have Roblox, what are you talking about? If you wanna unblock Roblox ask your teacher or something, not us

**Comment by pwksmsmsm** [comment] 2022-03-17 17:35
do u have unblocked doge miner 2

**Comment by Pepperoni-png** [comment] 2022-03-17 17:41
The proxies on the website are not guaranteed to work, they're more of a 50/50 chance, for example: coolmath games works but Roblox does not. If it's blocked, try some sort of unblocked site, however this won't work in Roblox's case since nobody has made an unblocked Roblox to my knowledge, and they can't since roblox is copyrighted.

As for dogeminer 2, try using the proxie to search dogeminer 2 then go there. I have not tested to see if that works yet.

If you want dogeminer 2 on the site, open an issue and send a request. I hope this helps you

**Comment by pwksmsmsm** [comment] 2022-03-17 17:46
what proxy

**Comment by Piplup7575** [comment] 2022-03-17 18:27
For dogeminer2 this is a dupe of #105 

Roblox doesn't work through proxys lmao, you need to download an app to run it.

**Closed by Piplup7575** 2022-03-17 18:27 UTC
Labels: ⛔ Blocked

**Comment by 3kh0** [comment] 2022-03-18 04:27
@pwksmsmsm the proxies are not made for Roblox, we will not nor ever will support Roblox, if you are wondering why, just look up people make games on YouTube

**Comment by pwksmsmsm** [comment] 2022-03-18 05:53
on the holy unblocker there is roblox

**Comment by pwksmsmsm** [comment] 2022-03-18 05:53
its on a website called now.gg
and its blocked
