### ISSUE TITLE
Bitlife is not working and this is the only game that is fun

### ISSUE THREAD

**Issue by kenken277** [3kh0/3kh0.github.io#128] opened 2022-03-09 00:51 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by Piplup7575** [comment] 2022-03-09 11:56
Screenshots please

**Comment by boomboomaladirt** [comment] 2022-03-11 01:00
bitlife is mid

**Comment by kenken277** [comment] 2022-03-11 01:45
> Screenshots please
[Note Mar 10, 2022.pdf](https://github.com/3kh0/3kh0.github.io/files/8228335/Note.Mar.10.2022.pdf)

**Comment by 3kh0** [comment] 2022-03-12 23:33
Duplicate of #118

**Closed by 3kh0** 2022-03-12 23:33 UTC
Labels: 🐜 Bug, 📄 Duplicate
