### ISSUE TITLE
Edys Car SImulator

### ISSUE THREAD

**Issue by Olivem1234567** [3kh0/3kh0.github.io#129] opened 2023-02-22 18:55 UTC
### What is this request?

New game

### Please describe the new feature here

 link : https://unblocked-games.s3.amazonaws.com/edys-car-simulator.html

**Comment by Russell2259** [comment] 2023-02-22 19:29
Duplicate of #103.

**Closed by Russell2259** 2023-02-22 19:29 UTC
Labels: 📄 Duplicate

**Comment by Olivem1234567** [comment] 2023-02-27 16:24
is it added?
