### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jefferysonn** [3kh0/3kh0.github.io#162] opened 2023-03-02 14:42 UTC
### What is this request?

New game

### If you said other in the dropdown above, please specify what below

https://bonk.io/

### Please describe the new feature here

echo please add bonk.io cus funny (ratio btw) (jkjk please dont wifi pineapple me)

**Comment by Russell2259** [comment] 2023-03-02 15:10
Duplicate of #68

**Closed by Russell2259** 2023-03-02 15:10 UTC
Labels: ✨ Enhancement
