### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [3kh0/3kh0.github.io#233] opened 2022-04-29 21:46 UTC
### What is this request?

New feature

### If you said other in the dropdown above, please specify what below

PLS DO NOT CLOSE.

### Please describe the new feature here

@3kh0 you should add proxies and vpns. Also anyone with the annoying blocker called relay smart agent can use this website. [](https://co-browsing.net/ url).It is the only proxy relay smart agent hasn’t blocked.You might also get inspiration from this website.[](https://sites.google.com/view/project-wolfpack/home url).All proxies and vpns on your discord are blocked.Some ppl need this proxy.PLS DO NOT CLOSE.

**Comment by 123345666777777777777777777777777** [comment] 2022-04-29 21:48
@3kh0 can you put this in the website and say that I helped.I don’t know how to create a pull request.

**Comment by Piplup7575** [comment] 2022-04-29 22:10
Dupe of #232

**Closed by Piplup7575** 2022-04-29 22:10 UTC
Labels: ✨ Enhancement

**Comment by 123345666777777777777777777777777** [comment] 2022-04-30 00:22
Dude Stop closing pls
