### ISSUE TITLE
Add YoHoHo.io

### ISSUE THREAD

**Issue by THEBEST1278** [3kh0/3kh0.github.io#222] opened 2022-04-23 18:53 UTC
### What is this request?

New game

### Please describe the new feature here

This is a fun game so it would be cool of you could add it.

**Comment by THEBEST1278** [comment] 2022-04-23 18:54
sry nvm someone already issued that :/

**Comment by Piplup7575** [comment] 2022-04-23 22:11
Dupe of 154

**Closed by Piplup7575** 2022-04-23 22:11 UTC
Labels: ✨ Enhancement
