### ISSUE TITLE
Game Request: FNAF Collection

### ISSUE THREAD

**Issue by TheEpicMainframe** [3kh0/3kh0.github.io#99] opened 2022-02-28 12:45 UTC
Please add any possible FNAF games you may find!

**Comment by Aspaceman527** [comment] 2022-02-28 14:53
like fnaf 2

**Comment by Piplup7575** [comment] 2022-02-28 14:59
dupe of #89 
just use this https://wellsousaaa.github.io/Five-Nights-at-Freddys-Web/

**Comment by 3kh0** [comment] 2022-02-28 22:04
What @Piplup7575 said,

**Closed by 3kh0** 2022-02-28 22:04 UTC
Labels: ✨ Enhancement

**Comment by JonnyKKid** [comment] 2022-03-02 03:05
Add any car game of your chouse
