### ISSUE TITLE
Zombs-Royale Not loading

### ISSUE THREAD

**Issue by derinpilge** [3kh0/3kh0.github.io#74] opened 2022-02-24 12:41 UTC
Chromebook
Chrome OS
When I go into zombs-royale, its just stuck loading, i deploy into games
Here's an image.

https://docs.google.com/document/d/1sw8wbEbsx2p2bo7ePB1dVSyQoqKJXxyRjIiTy2zPeTY/edit?usp=sharing

I've been afking for 25 minutes and it still hasn't loaded.
please help this was my favorite game as a child

**Comment by 3kh0** [comment] 2022-02-24 22:48
Duplicate of #67

**Closed by 3kh0** 2022-02-24 22:48 UTC
Labels: 🐜 Bug, ⚠ Invalid
