### ISSUE TITLE
Add a review

### ISSUE THREAD

**Issue by nxxh447** [3kh0/3kh0.github.io#467] opened 2022-12-14 12:54 UTC
### Name

Input on this project from me:

### Review

- why is there repeating google analytics code in `index.html`? it's unnecessary and pointless. it also just makes the already large document even bigger
- why are pull requests not being merged? you clearly view them, why not merge them?
- why are you not closing issues? you have an excessive buildup of issues and you've already seen all of them. example: https://github.com/3kh0/3kh0.github.io/issues/404

so I guess these are my recommendations, remove all instances of google analytic-related code from the `index.html` file except for one instance of it (well... so you can still get analytics). merge valid pull requests with the main branch and if there's something wrong with the request then address it, state what is wrong, and why you won't be merging. I would also like to add that your code analysis for merge proposals does not work, it fails almost every time. final thing, the profile picture field when creating new issues is pointless, and there is no "upload bar at the bottom of the input".

Edit (to include my point about issues):
close issues that are pointless, have already been solved/completed, or are no longer applicable. there is a large buildup of pointless issues.

### Profile picture

N/A

**Comment by 3kh0** [comment] 2022-12-14 14:34
Thanks for the feedback. Some of these pull requests still are in progress, and others I have request changes on. For the issues, I try to review every single one, when the game is added, the issue is closed. If you want to help, just mention me to close it if you think it is pointless. For the upload form, I can update that

**Comment by nxxh447** [comment] 2022-12-14 14:35
makes perfect sense 👍

**Closed** 2022-12-19 02:45 UTC
Labels: ✏️ Review
