### ISSUE TITLE
Zombs royale is broken [Bug] 

### ISSUE THREAD

**Issue by idkaname1** [3kh0/3kh0.github.io#102] opened 2023-02-14 01:00 UTC
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [X] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

it says "theadvancedsociety-tam.tbt.mx’s server IP address could not be found."

**Comment by Russell2259** [comment] 2023-02-14 01:20
Duplicate of #42

**Comment by 3kh0** [comment] 2023-02-14 21:07
Duplicate of https://github.com/3kh0/3kh0.github.io/issues/42

**Closed by 3kh0** 2023-02-14 21:07 UTC
Labels: 🐜 Bug, 📄 Duplicate
