### ISSUE TITLE
New Game

### ISSUE THREAD

**Issue by idkaname1** [3kh0/3kh0.github.io#96] opened 2023-02-13 00:05 UTC
### What is this request?

New game

### Please describe the new feature here

Can you please add Bonk.io to this awesome website?

**Comment by Russell2259** [comment] 2023-02-13 02:35
Duplicate of #68

**Comment by 3kh0** [comment] 2023-02-13 03:16
Duplicate of https://github.com/3kh0/3kh0.github.io/issues/68

**Closed by 3kh0** 2023-02-13 03:16 UTC
Labels: 📄 Duplicate, ✨ Enhancement
