### ISSUE TITLE
Bitlife was working but now it’s done

### ISSUE THREAD

**Issue by kenken277** [3kh0/3kh0.github.io#129] opened 2022-03-09 01:42 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by kenken277** [comment] 2022-03-09 01:42
I didn’t even get to play

**Comment by Piplup7575** [comment] 2022-03-09 11:56
Screenshots please?
It works fine for me.

**Comment by kenken277** [comment] 2022-03-11 01:43
> Screenshots please?
> It works fine for me.
[Note Mar 10, 2022.pdf](https://github.com/3kh0/3kh0.github.io/files/8228322/Note.Mar.10.2022.pdf)

**Comment by 3kh0** [comment] 2022-03-12 23:31
Duplicate of #118

**Closed by 3kh0** 2022-03-12 23:31 UTC
Labels: 🐜 Bug
