### ISSUE TITLE
Eaglercraft is not working

### ISSUE THREAD

**Issue by zek-c** [3kh0/3kh0.github.io#69] opened 2023-02-08 21:12 UTC
![Screenshot 2023-02-15 12 07 47 PM](https://user-images.githubusercontent.com/105883248/219141456-cb06c5f8-52da-484a-8509-b4d01c895335.png)
### Check these boxes to make sure you did everything right!

- [X] I have made sure that this issue does not already exist
- [X] I have submitted screenshots of the error
- [ ] You are not using the website on any clones (you are using 3kh0.github.io and nothing else)
- [ ] I just checked all of these boxes without reading the labels

### What browser are you using?

Google Chrome

### What device are you using?

Chromebook

### Please explain the issue

it crashes

**Comment by 3kh0** [comment] 2023-02-09 01:44
Thank you for reporting the issue you encountered while playing Eaglercraft. However, it is difficult for us to fully understand and diagnose the problem without any screenshots or crash logs. These types of files can provide valuable information about the nature of the crash and help us identify the root cause of the issue.

If possible, could you please provide us with any screenshots or crash logs related to the issue you are experiencing? This will greatly assist us in resolving the problem and ensuring a better gaming experience for you in the future.

**Comment by Piplup7575** [comment] 2023-02-11 21:00
imagine using chat gpt to respond to githib issues 🤮

**Comment by 3kh0** [comment] 2023-02-12 01:19
> imagine using chat gpt to respond to githib issues 🤮

stfu

**Comment by zek-c** [comment] 2023-02-15 20:08
> Thank you for reporting the issue you encountered while playing Eaglercraft. However, it is difficult for us to fully understand and diagnose the problem without any screenshots or crash logs. These types of files can provide valuable information about the nature of the crash and help us identify the root cause of the issue.
> 
> If possible, could you please provide us with any screenshots or crash logs related to the issue you are experiencing? This will greatly assist us in resolving the problem and ensuring a better gaming experience for you in the future.

i did

**Comment by 3kh0** [comment] 2023-02-16 13:54
You are using a different link than the main one, can you reproduce it on the main site?

**Comment by zek-c** [comment] 2023-02-16 17:39
wdym i cant use main its blocked by admin and wdym by reproduce

**Comment by 3kh0** [comment] 2023-02-17 02:33
Try this on the main site, and do it on a personal site perhaps

**Comment by Rahib777-7** [comment] 2023-02-21 05:18
try  a normal replit build (proxied)

**Comment by Bedrock435** [comment] 2023-02-22 21:40
Its been not working for me every time i try

**Comment by Bedrock435** [comment] 2023-02-22 21:41
![image](https://user-images.githubusercontent.com/126117475/220765648-9730e50c-0ad3-4f0d-813b-01ae550b5287.png)
:(

**Comment by host008** [comment] 2023-02-25 23:47
from the crash report, It might be because of the arc.io widget is blocked

**Comment by 3kh0** [comment] 2023-02-26 21:59
I might just remove the arc widget from eaglercraft, it causes alot of problems

**Comment by 3kh0** [comment] 2023-03-05 01:29
This has been fixed, please make sure your fork is up-to-date

**Closed by 3kh0** 2023-03-05 01:29 UTC
Labels: 🐜 Bug
