### ISSUE TITLE
Bit life

### ISSUE THREAD

**Issue by Topdawg0015** [3kh0/3kh0.github.io#135] opened 2022-03-09 18:10 UTC
**Describe the bug**
After a bit the website says limit reached
**To Reproduce**

**Expected behavior**

**Screenshots**
Please add any screenshots to help explain your problem.

**System information**

Operating system (eg ChromeOS or Windows):
Browser:

**Additional context**

**Comment by Piplup7575** [comment] 2022-03-09 21:57
yEs wE kNoW

**Comment by 3kh0** [comment] 2022-03-12 23:31
Duplicate of #118

**Closed by 3kh0** 2022-03-12 23:31 UTC
Labels: 🐜 Bug, 📄 Duplicate
