### ISSUE TITLE
game request

### ISSUE THREAD

**Issue by derinpilge** [3kh0/3kh0.github.io#191] opened 2022-04-04 22:37 UTC
### What is this request?

New game

### Please describe the new feature here

Talking ben (no url) work on it piplup lmao
ducklings io                              https://ducklings.io
agar io                                      https://agar.io
drift hunters                              https://drift-hunters.co/
yohoho(Ik ur working on it i saw it in projects)                      https://yohoho.io
headball 2                  (no url)
surviv io                                    https://surviv.io

notetoself:
e.e

**Comment by 3kh0** [comment] 2022-04-06 15:09
This is a duplicate of many requests we already have

**Closed by 3kh0** 2022-04-06 15:09 UTC
Labels: 📄 Duplicate, ✨ Enhancement
