### ISSUE TITLE
BITLIFE NOT WORKING!

### ISSUE THREAD

**Issue by LugCentral** [3kh0/3kh0.github.io#127] opened 2022-03-08 19:24 UTC
**Describe the bug**
When you play bitlife you can play for 20 mins then this pops up and its blocked.

![Screenshot 2022-03-08 14 21 07](https://user-images.githubusercontent.com/99853162/157309982-1675efb3-46db-4493-b627-7c22cd02e6cc.png)

**Comment by coolman3289** [comment] 2022-03-08 19:26
For me loads forever

**Comment by Piplup7575** [comment] 2022-03-08 20:07
Works for me

**Comment by LugCentral** [comment] 2022-03-09 13:33
Yeah Strange.. It is able to load for me but after 20 minutes or so it says limit reached. i will try to troubleshoot aka like clearing cookies to see if that works.

**Comment by 3kh0** [comment] 2022-03-12 23:33
Duplicate of #118

**Closed by 3kh0** 2022-03-12 23:33 UTC
Labels: 🐜 Bug, 📄 Duplicate
